import NavBar from './components/NavBar'
import Context from './context/Context'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UnderGround Code League',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  fetch(`api`).then(res => console.log(res))
  return (
    <Context>
      <html lang="en">
        <body className={` min-h-screen px-24 pb-10 bg-[hsl(240,10.2%,9.61%)] ${inter.className}`}>
          <NavBar />
          {children}
        </body>
      </html>
    </Context>
  )
}
